NumPy is a Python package which stands for ‘Numerical Python’. It is the core library for scientific computing, which contains a powerful n-dimensional array object, provide tools for integrating C, C++ etc. It is also useful in linear algebra, random number capability etc. NumPy array can also be used as an efficient multi-dimensional container for generic data.

# NumPy Array

 Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize numpy arrays from nested Python lists and access it elements. In order to perform these numpy operations

# Single-dimensional Numpy Array

In [1]:
import numpy as np

In [2]:
a=np.array([1,4,9,2,5,3])
a

array([1, 4, 9, 2, 5, 3])

# Multi-dimensional Array

In [3]:
a=np.array([(4,1,3),(3,9,7)])
a

array([[4, 1, 3],
       [3, 9, 7]])

In [4]:
a=np.array([[4,1,3],[3,9,7]])
a

array([[4, 1, 3],
       [3, 9, 7]])

# Python NumPy Array v/s List

We use python numpy array instead of a list because of the below three reasons:       
1.Less Memory    
2.Fast       
3.Convenient

# 1.Less Memory

The very first reason to choose python numpy array is that it occupies less memory as compared to list.

In [5]:
import sys
S= range(1000)
print("Memory Required for storing 1000 elements using list is :",sys.getsizeof(5)*len(S),"Bytes")
 
D= np.arange(1000)
print("Memory Required for storing 1000 elements using NumPy is :",D.size*D.itemsize,"Bytes")

Memory Required for storing 1000 elements using list is : 28000 Bytes
Memory Required for storing 1000 elements using NumPy is : 4000 Bytes


The above output shows that the memory allocation of each element requires 14 bytes by list and for Numpy it requires 4 bytes

# 2.Fast

In [6]:
import time

 
SIZE = 1000000
 
L1= range(SIZE)
L2= range(SIZE)
A1= np.arange(SIZE)
A2=np.arange(SIZE)
 #Addition using Python List
start= time.time()
result=[(x+y) for x,y in zip(L1,L2)]
print("Addition Using Python List for 1000000 element requires : ",(time.time()-start)*1000,"Miliseconds")
 
    #Addition using Numpy
start=time.time()
result= A1+A2
print("Addition Using NumPy for 1000000 element requires : ",(time.time()-start)*1000,"Miliseconds")

Addition Using Python List for 1000000 element requires :  132.69734382629395 Miliseconds
Addition Using NumPy for 1000000 element requires :  18.88275146484375 Miliseconds


# 3.Convenient

Lets do some numeric operation on NumPy

In [7]:
a=np.array([3,5,1,6,9])

In [8]:
a[3]

6

In [9]:
a1=np.array([3,5,1])
a2=np.array([2,1,4])

In [10]:
a1+a2

array([5, 6, 5])

In [11]:
a1-a2

array([ 1,  4, -3])

In [12]:
a1/a2

array([1.5 , 5.  , 0.25])

In [13]:
a1*a2

array([6, 5, 4])

# Python NumPy Operations

# ndim

You can find the dimension of the array, whether it is a two-dimensional array or a single dimensional array. 

In [14]:
a=np.array([1,4,9,2,5,3])

In [15]:
a.ndim

1

In [16]:
a=np.array([[4,1,3],[3,9,7]])
a.ndim

2

In [17]:
a=np.array([[4,1,3],[3,9,7],[2,3,8]])
a.ndim

2

In [18]:
a = np.array([(1,2,3),(4,5,6),(4,1,3)])
a.ndim

2

# itemsize

You can calculate the byte size of each element. In the below code,  with the help of ‘itemsize’ function, we can find the size of each element.

In [19]:
a = np.array([(1,2,3)])
print(a.itemsize)

4


# ‘size’ and ‘shape’

In [20]:
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


# reshape

Reshape is when you change the number of rows and columns which gives a new view to an object.

In [21]:
a = np.array([(8,9,10),(11,12,13)])
print(a)
print("Shape of array is :",a.shape)

[[ 8  9 10]
 [11 12 13]]
Shape of array is : (2, 3)


In [22]:
a=a.reshape(3,2)
print(a)
print("Re-Shape of array is :",a.shape)

[[ 8  9]
 [10 11]
 [12 13]]
Re-Shape of array is : (3, 2)


# slicing

Slicing is basically extracting particular set of elements from an array.        Before getting into the above example, let’s see a simple one. We have an array and we need a particular element (say 3) out of a given array. Let’s consider the below example:

In [23]:
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a)
print("Shape of array is :",a.shape)
print(a[0,2])

[[1 2 3 4]
 [3 4 5 6]]
Shape of array is : (2, 4)
3


Here, the array(1,2,3,4) is your index 0 and (3,4,5,6) is index 1 of the python numpy array. Therefore, we have printed the second element from the zeroth index.
Taking one step forward, let’s say we need the 2nd element from the zeroth and first index of the array. Let’s see how you can perform this operation:

In [24]:
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a)
print(a[0:,2])

[[1 2 3 4]
 [3 4 5 6]]
[3 5]


Here colon represents all the rows, including zero. Now to get the 2nd element, we’ll call index 2 from both of the rows which gives us the value 3 and 5 respectively.

In [25]:
a=np.array([(8,9),(10,11),(12,13)])
print(a)
print(a[0:2,1])

[[ 8  9]
 [10 11]
 [12 13]]
[ 9 11]


# linspace 

This is another operation in python numpy which returns evenly spaced numbers over a specified interval. Consider the below example:

In [26]:
a=np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


As you can see in the result, it has printed 10 values between 1 to 3.

# max/ min/sum/mean

In [27]:
a= np.array([1,2,3])
print(a)
print("Minimum of array :",a.min())
print("Maximum of array :",a.max())
print("Sum of array :",a.sum())
print("Mean of array :",a.mean())

[1 2 3]
Minimum of array : 1
Maximum of array : 3
Sum of array : 6
Mean of array : 2.0


# axis 

The rows are called as axis 1 and the columns are called as axis 0

In [28]:
a= np.array([(1,2,3),(3,4,5)])
print(a)

print("Sum of Column or axis 0 is : ",a.sum(axis=0))

[[1 2 3]
 [3 4 5]]
Sum of Column or axis 0 is :  [4 6 8]


# Square Root & Standard Deviation

In [29]:
a=np.array([(1,2,3),(3,4,5,)])
print(a)
print("Square Root:",np.sqrt(a))
print("Standard Deviation:",np.std(a))

[[1 2 3]
 [3 4 5]]
Square Root: [[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
Standard Deviation: 1.2909944487358056


# Vertical & Horizontal Stacking

if you want to concatenate two arrays , you can perform it using two ways – vertical stacking and horizontal stacking. 

In [30]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(0,7,6),(2,1,4)])
print("First array is :")
print(x)
print("Second array is :")
print(y)
print("Vertical stack array is :")
print(np.vstack((x,y)))
print("Horizontal stack array is :")
print(np.hstack((x,y)))

First array is :
[[1 2 3]
 [3 4 5]]
Second array is :
[[0 7 6]
 [2 1 4]]
Vertical stack array is :
[[1 2 3]
 [3 4 5]
 [0 7 6]
 [2 1 4]]
Horizontal stack array is :
[[1 2 3 0 7 6]
 [3 4 5 2 1 4]]


# Python Numpy Special Functions

In [31]:
array1 = np.arange(0,10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
array1 = np.arange(12).reshape(3,4)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
array1[3:6]

array([3, 4, 5])

Index ‘3’ represents the starting element of the slice and it's inclusive. Index ‘6’ represents the stopping element of the slice and it’s exclusive.

# If you do not specify the starting and the stopping index you will get all the values. 

In [35]:
array1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

That's because if the indices are missing, by default, Numpy inserts the starting and stopping indices that select the entire array. So writing array1[:] is equivalent to writing array1[0:10]

You can extend this concept to include only the starting index. In this case, the slice includes all the elements from the starting index until the end of the array.

In [36]:
array1[4:]

array([4, 5, 6, 7, 8, 9])

Or, alternatively, specify only the stopping index.

In [37]:
array1[:7]

array([0, 1, 2, 3, 4, 5, 6])

# Using Negative Indices

In [38]:
array1 = np.array([10,20,30,40,50,60,70,80,90])
array1


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

[10, 20, 30, 40, 50, 60, 70, 80, 90]   
        0,  1,  2,  3,  4,  5,  6,  7,  8   
        0,  -8, -7, -6, -5, -4, -3, -2, -1 

In [39]:
array1[-6]

40

In [40]:
array1[3:-2]

array([40, 50, 60, 70])

In [41]:
array1[-3:-1]

array([70, 80])

# Using Step Index

In [42]:
array1 = np.array([10,20,30,40,50,60,70,80,90])
array1


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
array1[2:6:3]

array([30, 60])

# Slicing a Two-dimensional Array

In [44]:
array1 = np.arange(16).reshape(4,4)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
array1[0:2, 1:3]

array([[1, 2],
       [5, 6]])